services:
  postgres:
    container_name: postgres
    image: postgres:13
    networks:
      - hackings_api_network
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    hostname: postgres
  adonis_app:
    container_name: api
    networks:
      - hackings_api_network
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 5173:5173
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: dumb-init npm run dev --host

volumes:
  postgres_volume:

networks:
  hackings_api_network:
    driver: bridge
