services:
  api:
    build:
      dockerfile: .docker/api/Dockerfile
      context: .
      target: dependencies
    restart: unless-stopped
    expose:
      - 3333
    ports:
      - 3333:3333
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
      - /usr/src/app/.docker
    networks:
      - hacklings_api_network
    command: npm run dev
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - .docker/tmp/postgres_data:/var/lib/postgresql/data
    networks:
      - hacklings_api_network


networks:
  hacklings_api_network:
    driver: bridge
